# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhenoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenoid', models.CharField(max_length=64)),
                ('phenogene', models.CharField(max_length=20)),
                ('phenoilln', models.CharField(max_length=150)),
            ],
        ),
    ]
